use_default_settings: true

server:
  secret_key: "85fc6af96e05be08d4bc5c8f73214cd90e62e18d53c2391afc64de50f8543b73"
  limiter: false
  image_proxy: false

search:
  safe_search: 0
  formats:
    - html
    - json

engines:
  - name: google
    engine: google
    shortcut: g
    language: fr
  - name: bing
    engine: bing
    shortcut: b
  - name: duckduckgo
    engine: duckduckgo
    shortcut: d
